#!/bin/sh

# Set these paths appropriately

BIN=/Volumes/DATA/Work/tools/heideltime/treetagger/bin
CMD=/Volumes/DATA/Work/tools/heideltime/treetagger/cmd
LIB=/Volumes/DATA/Work/tools/heideltime/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

