#!/bin/sh

# Set these paths appropriately

BIN=/Volumes/DATA/Work/tools/heideltime/treetagger/bin
CMD=/Volumes/DATA/Work/tools/heideltime/treetagger/cmd
LIB=/Volumes/DATA/Work/tools/heideltime/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
