#!/bin/sh

# Set these paths appropriately

BIN=/Volumes/DATA/Work/tools/heideltime/treetagger/bin
CMD=/Volumes/DATA/Work/tools/heideltime/treetagger/cmd
LIB=/Volumes/DATA/Work/tools/heideltime/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
