#!/bin/sh

# Set these paths appropriately

BIN=/Volumes/DATA/Work/tools/heideltime/treetagger/bin
CMD=/Volumes/DATA/Work/tools/heideltime/treetagger/cmd
LIB=/Volumes/DATA/Work/tools/heideltime/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/estonian-abbreviations
PARFILE=${LIB}/estonian.par
MWLFILE=${LIB}/estonian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE

