#!/bin/sh

# Set these paths appropriately

BIN=/Volumes/DATA/Work/tools/heideltime/treetagger/bin
CMD=/Volumes/DATA/Work/tools/heideltime/treetagger/cmd
LIB=/Volumes/DATA/Work/tools/heideltime/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
